"use strict";
var Enums_1 = require("./Enums");
/**
 * Created by Fei on 08/03/2017.
 */
var Constants = (function () {
    function Constants() {
    }
    Constants.TEMP_PASSWORD = "testtest";
    Constants.ALERT_DURATION = 5000;
    /*PATHS*/
    Constants.APP_STATUS = "/sand";
    Constants.LOGIN_PATH = "/login";
    //system admin
    Constants.DEFAULT_MPA_PATH = "/system-admin/mpa";
    Constants.SYSTEM_ADMIN_HOME = "/system-admin/agency";
    Constants.SYSTEM_ADMIN_NETWORK_HOME = "/system-admin/network";
    Constants.SYSTEM_ADMIN_ADD_NETWORK = "/system-admin/network/create";
    //agency admin
    Constants.AGENCY_ADMIN_HOME = "/agency-admin/country-office";
    Constants.AGENCY_ADMIN_ADD_STARFF = "/agency-admin/staff/create-edit-staff";
    Constants.AGENCY_ADMIN_STARFF = "/agency-admin/staff";
    Constants.AGENCY_ADMIN_LOGO_MAX_SIZE = 2000000; //in bytes
    Constants.AGENCY_ADMIN_LOGO_FILE_TYPES = ['image/jpeg', 'image/gif', 'image/png'];
    /*LIST VALUES FOR TRANSLATION*/
    Constants.THRESHOLD_VALUE = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95];
    Constants.PERSON_TITLE = ["GLOBAL.PERSON_TITLE.MR", "GLOBAL.PERSON_TITLE.MRS", "GLOBAL.PERSON_TITLE.MISS",
        "GLOBAL.PERSON_TITLE.DR", "GLOBAL.PERSON_TITLE.PROF"];
    Constants.PERSON_TITLE_SELECTION = [Enums_1.PersonTitle.Mr, Enums_1.PersonTitle.Miss, Enums_1.PersonTitle.Dr];
    Constants.COUNTRY = ["GLOBAL.COUNTRY.UK", "GLOBAL.COUNTRY.FRANCE", "GLOBAL.COUNTRY.GERMANY"];
    Constants.COUNTRY_SELECTION = [Enums_1.Country.UK, Enums_1.Country.France, Enums_1.Country.Germany];
    Constants.CATEGORY = [
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.ALL",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY0",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY1",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY2",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY3",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY4",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY5",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY6",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY7",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY8",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY9"];
    Constants.ACTION_LEVEL = ["GLOBAL.PREPAREDNESS_LEVEL.ALL", "GLOBAL.PREPAREDNESS_LEVEL.MPA", "GLOBAL.PREPAREDNESS_LEVEL.APA"];
    Constants.CURRENCY = ["GBP", "EUR", "USD"];
    Constants.CURRENCY_SELECTION = [Enums_1.Currency.GBP, Enums_1.Currency.EUR, Enums_1.Currency.USD];
    Constants.USER_TYPE = ["All users", "GLOBAL.USER_TYPE.GLOBAL_DIRECTOR", "GLOBAL.USER_TYPE.REGIONAL_DIRECTOR",
        "GLOBAL.USER_TYPE.COUNTRY_DIRECTORS", "GLOBAL.USER_TYPE.ERT_LEAD", "GLOBAL.USER_TYPE.ERT", "GLOBAL.USER_TYPE.DONOR",
        "GLOBAL.USER_TYPE.GLOBAL_USER", "GLOBAL.USER_TYPE.COUNTRY_ADMINS"];
    Constants.USER_TYPE_SELECTION = [Enums_1.UserType.All, Enums_1.UserType.GlobalDirector, Enums_1.UserType.RegionalDirector, Enums_1.UserType.CountryDirector,
        Enums_1.UserType.ErtLeader, Enums_1.UserType.Ert, Enums_1.UserType.Donor, Enums_1.UserType.GlobalUser, Enums_1.UserType.CountryAdmin];
    Constants.STAFF_POSITION = ["AGENCY_ADMIN.STAFF.ALL_POSITIONS", "AGENCY_ADMIN.STAFF.OFFICE_DIRECTOR", "AGENCY_ADMIN.STAFF.OFFICE_STAFF"];
    Constants.STAFF_POSITION_SELECTION = [Enums_1.StaffPosition.All, Enums_1.StaffPosition.OfficeDirector, Enums_1.StaffPosition.OfficeStarff];
    Constants.OFFICE_TYPE = ["AGENCY_ADMIN.STAFF.ALL_OFFICES", "AGENCY_ADMIN.STAFF.FIELD_OFFICE", "AGENCY_ADMIN.STAFF.LAB_OFFICE"];
    Constants.OFFICE_TYPE_SELECTION = [Enums_1.OfficeType.All, Enums_1.OfficeType.FieldOffice, Enums_1.OfficeType.LabOffice];
    Constants.MODULE_NAME = [
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.MINIMUM_PREP_ACTIONS",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.ADVANCED_PREP_ACTIONS",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.CHS_PREP_ACTIONS",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.HAZAR_PRIORITISATION",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.PREP_BUDGET",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.SEASONAL_CALENDAR",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.HAZARD_INDICATOR",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.COUNTRY_OFFICE_PROFILE",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.RESPONSE_PLANNING",
        "AGENCY_ADMIN.SETTINGS.MODULE_NAME.GLOBAL_MAPS"
    ];
    Constants.DURATION_TYPE = [
        "AGENCY_ADMIN.SETTINGS.DURATION_TYPE.WEEKS",
        "AGENCY_ADMIN.SETTINGS.DURATION_TYPE.MONTHS",
        "AGENCY_ADMIN.SETTINGS.DURATION_TYPE.YEARS"
    ];
    Constants.DURATION_TYPE_SELECTION = [Enums_1.DurationType.Week, Enums_1.DurationType.Month, Enums_1.DurationType.Year];
    Constants.NOTIFICATION_SETTINGS = ["GLOBAL.NOTIFICATION_SETTING.ALERT_LEVEL_CHANGE", "GLOBAL.NOTIFICATION_SETTING.RED_ALERT_REQUEST",
        "GLOBAL.NOTIFICATION_SETTING.UPDATE_HAZARD", "GLOBAL.NOTIFICATION_SETTING.ACTION_EXPIRE",
        "GLOBAL.NOTIFICATION_SETTING.RESPONSE_PLAN_EXPIRE", "GLOBAL.NOTIFICATION_SETTING.RESPONSE_PLAN_REJECT"];
    Constants.GROUP_PATH_AGENCY = ["globaldirector", "regionaldirector", "countrydirectors", "ertleads", "erts", "donor", "globaluser", "countryadmins"];
    /*
     * Response Plans
     */
    Constants.HAZARD_SCENARIOS = [
        "RESPONSE_PLANS.HAZARD_SCENARIO0.HAZARD_SCENARIO0",
        "RESPONSE_PLANS.HAZARD_SCENARIO1.HAZARD_SCENARIO1",
        "RESPONSE_PLANS.HAZARD_SCENARIO2.HAZARD_SCENARIO2",
        "RESPONSE_PLANS.HAZARD_SCENARIO3.HAZARD_SCENARIO3",
        "RESPONSE_PLANS.HAZARD_SCENARIO4.HAZARD_SCENARIO4",
        "RESPONSE_PLANS.HAZARD_SCENARIO5.HAZARD_SCENARIO5",
        "RESPONSE_PLANS.HAZARD_SCENARIO6.HAZARD_SCENARIO6",
        "RESPONSE_PLANS.HAZARD_SCENARIO7.HAZARD_SCENARIO7",
        "RESPONSE_PLANS.HAZARD_SCENARIO8.HAZARD_SCENARIO8",
        "RESPONSE_PLANS.HAZARD_SCENARIO9.HAZARD_SCENARIO9",
        "RESPONSE_PLANS.HAZARD_SCENARIO10.HAZARD_SCENARIO10"
    ];
    Constants.RESPONSE_PLANS_SECTION_SETTINGS = [
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.PLAN_DETAILS",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.PLAN_CONTEXT",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.BASIC_INFORMATION",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.ACTIVITY_SUMMARY",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.TARGET_POPULATION",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.EXPECTED_RESULTS",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.ACTIVITIES",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.MONITORING_ACC_LEARNING",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.DOUBLE_COUNTING",
        "AGENCY_ADMIN.SETTINGS.RESPONSE_PLAN_SECTION_SETTINGS.BUDGET"
    ];
    return Constants;
}());
exports.Constants = Constants;
(function (FILE_SETTING) {
    FILE_SETTING[FILE_SETTING["PDF"] = 0] = "PDF";
    FILE_SETTING[FILE_SETTING["DOC"] = 1] = "DOC";
    FILE_SETTING[FILE_SETTING["DOCX"] = 2] = "DOCX";
    FILE_SETTING[FILE_SETTING["RTF"] = 3] = "RTF";
    FILE_SETTING[FILE_SETTING["JPEG"] = 4] = "JPEG";
    FILE_SETTING[FILE_SETTING["PNG"] = 5] = "PNG";
    FILE_SETTING[FILE_SETTING["CSV"] = 6] = "CSV";
    FILE_SETTING[FILE_SETTING["XLS"] = 7] = "XLS";
    FILE_SETTING[FILE_SETTING["XLSX"] = 8] = "XLSX";
    FILE_SETTING[FILE_SETTING["PPT"] = 9] = "PPT";
    FILE_SETTING[FILE_SETTING["PPTX"] = 10] = "PPTX";
    FILE_SETTING[FILE_SETTING["TXT"] = 11] = "TXT";
    FILE_SETTING[FILE_SETTING["ODT"] = 12] = "ODT";
    FILE_SETTING[FILE_SETTING["TSV"] = 13] = "TSV";
})(exports.FILE_SETTING || (exports.FILE_SETTING = {}));
var FILE_SETTING = exports.FILE_SETTING;
