"use strict";
var Enums_1 = require("./Enums");
/**
 * Created by Fei on 08/03/2017.
 */
var Constants = (function () {
    function Constants() {
    }
    Constants.TEMP_PASSWORD = "testtest";
    /*PATHS*/
    Constants.APP_STATUS = "/sand";
    Constants.LOGIN_PATH = "/login";
    //system admin
    Constants.DEFAULT_MPA_PATH = "/system-admin/mpa";
    Constants.SYSTEM_ADMIN_HOME = "/system-admin/agency";
    Constants.SYSTEM_ADMIN_NETWORK_HOME = "/system-admin/network";
    Constants.SYSTEM_ADMIN_ADD_NETWORK = "/system-admin/network/create";
    //agency admin
    Constants.AGENCY_ADMIN_HOME = "/agency-admin/country-office";
    Constants.AGENCY_ADMIN_ADD_STARFF = "/agency-admin/staff/create-edit-staff";
    Constants.ALERT_DURATION = 5000;
    Constants.AGENCY_ADMIN_STARFF = "/agency-admin/staff";
    /*LIST VALUES FRO TRANSLATION*/
    Constants.THRESHOLD_VALUE = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95];
    Constants.PERSON_TITLE = ["GLOBAL.PERSON_TITLE.MR", "GLOBAL.PERSON_TITLE.MRS", "GLOBAL.PERSON_TITLE.MISS",
        "GLOBAL.PERSON_TITLE.DR", "GLOBAL.PERSON_TITLE.PROF"];
    Constants.PERSON_TITLE_SELECTION = [Enums_1.PersonTitle.Mr, Enums_1.PersonTitle.Miss, Enums_1.PersonTitle.Dr];
    Constants.COUNTRY = ["GLOBAL.COUNTRY.UK", "GLOBAL.COUNTRY.FRANCE", "GLOBAL.COUNTRY.GERMANY"];
    Constants.COUNTRY_SELECTION = [Enums_1.Country.UK, Enums_1.Country.France, Enums_1.Country.Germany];
    Constants.CATEGORY = ["SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.ALL", "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY0", "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY1",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY2", "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY3", "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY4",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY5", "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY6", "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY7",
        "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY8", "SYSTEM_ADMIN.ACTIONS.GENERIC_MPA_APA.CATEGORIES.CATEGORY9"];
    Constants.ACTION_LEVEL = ["GLOBAL.PREPAREDNESS_LEVEL.ALL", "GLOBAL.PREPAREDNESS_LEVEL.MPA", "GLOBAL.PREPAREDNESS_LEVEL.APA"];
    return Constants;
}());
exports.Constants = Constants;
(function (FILE_SETTING) {
    FILE_SETTING[FILE_SETTING["PDF"] = 0] = "PDF";
    FILE_SETTING[FILE_SETTING["DOC"] = 1] = "DOC";
    FILE_SETTING[FILE_SETTING["DOCX"] = 2] = "DOCX";
    FILE_SETTING[FILE_SETTING["RTF"] = 3] = "RTF";
    FILE_SETTING[FILE_SETTING["JPEG"] = 4] = "JPEG";
    FILE_SETTING[FILE_SETTING["PNG"] = 5] = "PNG";
    FILE_SETTING[FILE_SETTING["CSV"] = 6] = "CSV";
    FILE_SETTING[FILE_SETTING["XLS"] = 7] = "XLS";
    FILE_SETTING[FILE_SETTING["XLSX"] = 8] = "XLSX";
    FILE_SETTING[FILE_SETTING["PPT"] = 9] = "PPT";
    FILE_SETTING[FILE_SETTING["PPTX"] = 10] = "PPTX";
    FILE_SETTING[FILE_SETTING["TXT"] = 11] = "TXT";
    FILE_SETTING[FILE_SETTING["ODT"] = 12] = "ODT";
    FILE_SETTING[FILE_SETTING["TSV"] = 13] = "TSV";
})(exports.FILE_SETTING || (exports.FILE_SETTING = {}));
var FILE_SETTING = exports.FILE_SETTING;
