"use strict";
/**
 * Created by Sanjaya on 07/03/2017.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var ActionType;
(function (ActionType) {
    ActionType[ActionType["chs"] = 0] = "chs";
    ActionType[ActionType["mandated"] = 1] = "mandated";
    ActionType[ActionType["custom"] = 2] = "custom";
})(ActionType = exports.ActionType || (exports.ActionType = {}));
// TODO - Update when Ryan provides actual Category names
var GenericActionCategory;
(function (GenericActionCategory) {
    GenericActionCategory[GenericActionCategory["ALL"] = 0] = "ALL";
    GenericActionCategory[GenericActionCategory["Category1"] = 1] = "Category1";
    GenericActionCategory[GenericActionCategory["Category2"] = 2] = "Category2";
    GenericActionCategory[GenericActionCategory["Category3"] = 3] = "Category3";
    GenericActionCategory[GenericActionCategory["Category4"] = 4] = "Category4";
    GenericActionCategory[GenericActionCategory["Category5"] = 5] = "Category5";
    GenericActionCategory[GenericActionCategory["Category6"] = 6] = "Category6";
    GenericActionCategory[GenericActionCategory["Category7"] = 7] = "Category7";
    GenericActionCategory[GenericActionCategory["Category8"] = 8] = "Category8";
    GenericActionCategory[GenericActionCategory["Category9"] = 9] = "Category9";
    GenericActionCategory[GenericActionCategory["Category10"] = 10] = "Category10";
})(GenericActionCategory = exports.GenericActionCategory || (exports.GenericActionCategory = {}));
// TODO - Update when Ryan provides actual Hazard Scenario names
var HazardScenario;
(function (HazardScenario) {
    HazardScenario[HazardScenario["HazardScenario0"] = 0] = "HazardScenario0";
    HazardScenario[HazardScenario["HazardScenario1"] = 1] = "HazardScenario1";
    HazardScenario[HazardScenario["HazardScenario2"] = 2] = "HazardScenario2";
    HazardScenario[HazardScenario["HazardScenario3"] = 3] = "HazardScenario3";
    HazardScenario[HazardScenario["HazardScenario4"] = 4] = "HazardScenario4";
    HazardScenario[HazardScenario["HazardScenario5"] = 5] = "HazardScenario5";
    HazardScenario[HazardScenario["HazardScenario6"] = 6] = "HazardScenario6";
    HazardScenario[HazardScenario["HazardScenario7"] = 7] = "HazardScenario7";
    HazardScenario[HazardScenario["HazardScenario8"] = 8] = "HazardScenario8";
    HazardScenario[HazardScenario["HazardScenario9"] = 9] = "HazardScenario9";
    HazardScenario[HazardScenario["HazardScenario10"] = 10] = "HazardScenario10";
    HazardScenario[HazardScenario["HazardScenario11"] = 11] = "HazardScenario11";
    HazardScenario[HazardScenario["HazardScenario12"] = 12] = "HazardScenario12";
    HazardScenario[HazardScenario["HazardScenario13"] = 13] = "HazardScenario13";
    HazardScenario[HazardScenario["HazardScenario14"] = 14] = "HazardScenario14";
    HazardScenario[HazardScenario["HazardScenario15"] = 15] = "HazardScenario15";
    HazardScenario[HazardScenario["HazardScenario16"] = 16] = "HazardScenario16";
    HazardScenario[HazardScenario["HazardScenario17"] = 17] = "HazardScenario17";
    HazardScenario[HazardScenario["HazardScenario18"] = 18] = "HazardScenario18";
    HazardScenario[HazardScenario["HazardScenario19"] = 19] = "HazardScenario19";
    HazardScenario[HazardScenario["HazardScenario20"] = 20] = "HazardScenario20";
    HazardScenario[HazardScenario["HazardScenario21"] = 21] = "HazardScenario21";
    HazardScenario[HazardScenario["HazardScenario22"] = 22] = "HazardScenario22";
    HazardScenario[HazardScenario["HazardScenario23"] = 23] = "HazardScenario23";
    HazardScenario[HazardScenario["HazardScenario24"] = 24] = "HazardScenario24";
    HazardScenario[HazardScenario["HazardScenario25"] = 25] = "HazardScenario25";
    HazardScenario[HazardScenario["HazardScenario26"] = 26] = "HazardScenario26";
})(HazardScenario = exports.HazardScenario || (exports.HazardScenario = {}));
var ActionLevel;
(function (ActionLevel) {
    ActionLevel[ActionLevel["ALL"] = 0] = "ALL";
    ActionLevel[ActionLevel["MPA"] = 1] = "MPA";
    ActionLevel[ActionLevel["APA"] = 2] = "APA";
})(ActionLevel = exports.ActionLevel || (exports.ActionLevel = {}));
var PersonTitle;
(function (PersonTitle) {
    PersonTitle[PersonTitle["Mr"] = 0] = "Mr";
    PersonTitle[PersonTitle["Mrs"] = 1] = "Mrs";
    PersonTitle[PersonTitle["Miss"] = 2] = "Miss";
    PersonTitle[PersonTitle["Dr"] = 3] = "Dr";
    PersonTitle[PersonTitle["Prof"] = 4] = "Prof";
})(PersonTitle = exports.PersonTitle || (exports.PersonTitle = {}));
var FileType;
(function (FileType) {
    FileType[FileType["MB"] = 0] = "MB";
    FileType[FileType["GB"] = 1] = "GB";
})(FileType = exports.FileType || (exports.FileType = {}));
var Country;
(function (Country) {
    Country[Country["UK"] = 0] = "UK";
    Country[Country["France"] = 1] = "France";
    Country[Country["Germany"] = 2] = "Germany";
})(Country = exports.Country || (exports.Country = {}));
var Currency;
(function (Currency) {
    Currency[Currency["GBP"] = 0] = "GBP";
    Currency[Currency["EUR"] = 1] = "EUR";
    Currency[Currency["USD"] = 2] = "USD";
})(Currency = exports.Currency || (exports.Currency = {}));
var StaffPosition;
(function (StaffPosition) {
    StaffPosition[StaffPosition["All"] = 0] = "All";
    StaffPosition[StaffPosition["OfficeDirector"] = 1] = "OfficeDirector";
    StaffPosition[StaffPosition["OfficeStarff"] = 2] = "OfficeStarff";
})(StaffPosition = exports.StaffPosition || (exports.StaffPosition = {}));
var UserType;
(function (UserType) {
    UserType[UserType["All"] = 0] = "All";
    UserType[UserType["GlobalDirector"] = 1] = "GlobalDirector";
    UserType[UserType["RegionalDirector"] = 2] = "RegionalDirector";
    UserType[UserType["CountryDirector"] = 3] = "CountryDirector";
    UserType[UserType["ErtLeader"] = 4] = "ErtLeader";
    UserType[UserType["Ert"] = 5] = "Ert";
    UserType[UserType["Donor"] = 6] = "Donor";
    UserType[UserType["GlobalUser"] = 7] = "GlobalUser";
    UserType[UserType["CountryAdmin"] = 8] = "CountryAdmin";
    UserType[UserType["NonAlert"] = 9] = "NonAlert";
})(UserType = exports.UserType || (exports.UserType = {}));
var OfficeType;
(function (OfficeType) {
    OfficeType[OfficeType["All"] = 0] = "All";
    OfficeType[OfficeType["FieldOffice"] = 1] = "FieldOffice";
    OfficeType[OfficeType["LabOffice"] = 2] = "LabOffice";
})(OfficeType = exports.OfficeType || (exports.OfficeType = {}));
var SkillType;
(function (SkillType) {
    SkillType[SkillType["Support"] = 0] = "Support";
    SkillType[SkillType["Tech"] = 1] = "Tech";
})(SkillType = exports.SkillType || (exports.SkillType = {}));
var NotificationSettingEvents;
(function (NotificationSettingEvents) {
    NotificationSettingEvents[NotificationSettingEvents["AlertLevelChanged"] = 0] = "AlertLevelChanged";
    NotificationSettingEvents[NotificationSettingEvents["RedAlertRequest"] = 1] = "RedAlertRequest";
    NotificationSettingEvents[NotificationSettingEvents["UpdateHazard"] = 2] = "UpdateHazard";
    NotificationSettingEvents[NotificationSettingEvents["ActionExpired"] = 3] = "ActionExpired";
    NotificationSettingEvents[NotificationSettingEvents["PlanExpired"] = 4] = "PlanExpired";
    NotificationSettingEvents[NotificationSettingEvents["PlanRejected"] = 5] = "PlanRejected";
})(NotificationSettingEvents = exports.NotificationSettingEvents || (exports.NotificationSettingEvents = {}));
var Privacy;
(function (Privacy) {
    Privacy[Privacy["Public"] = 0] = "Public";
    Privacy[Privacy["Private"] = 1] = "Private";
    Privacy[Privacy["Network"] = 2] = "Network";
})(Privacy = exports.Privacy || (exports.Privacy = {}));
var DurationType;
(function (DurationType) {
    DurationType[DurationType["Week"] = 0] = "Week";
    DurationType[DurationType["Month"] = 1] = "Month";
    DurationType[DurationType["Year"] = 2] = "Year";
})(DurationType = exports.DurationType || (exports.DurationType = {}));
var Location;
(function (Location) {
    Location[Location["Philippines"] = 0] = "Philippines";
    Location[Location["Malaysia"] = 1] = "Malaysia";
    Location[Location["Indonesia"] = 2] = "Indonesia";
})(Location = exports.Location || (exports.Location = {}));
var DocumentType;
(function (DocumentType) {
    DocumentType[DocumentType["MPA"] = 0] = "MPA";
    DocumentType[DocumentType["APA"] = 1] = "APA";
    DocumentType[DocumentType["ResponsePlan"] = 2] = "ResponsePlan";
    DocumentType[DocumentType["Hazard"] = 3] = "Hazard";
})(DocumentType = exports.DocumentType || (exports.DocumentType = {}));
/**
 * Response Plans
 */
var ResponsePlanSectionSettings;
(function (ResponsePlanSectionSettings) {
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["PlanDetails"] = 0] = "PlanDetails";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["PlanContext"] = 1] = "PlanContext";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["BasicInformation"] = 2] = "BasicInformation";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["ActivitySummary"] = 3] = "ActivitySummary";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["TargetPopulation"] = 4] = "TargetPopulation";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["ExpectedResults"] = 5] = "ExpectedResults";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["Activities"] = 6] = "Activities";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["MonitoringAccLearning"] = 7] = "MonitoringAccLearning";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["DoubleCounting"] = 8] = "DoubleCounting";
    ResponsePlanSectionSettings[ResponsePlanSectionSettings["Budget"] = 9] = "Budget";
})(ResponsePlanSectionSettings = exports.ResponsePlanSectionSettings || (exports.ResponsePlanSectionSettings = {}));
var ResponsePlanSectors;
(function (ResponsePlanSectors) {
    ResponsePlanSectors[ResponsePlanSectors["wash"] = 0] = "wash";
    ResponsePlanSectors[ResponsePlanSectors["health"] = 1] = "health";
    ResponsePlanSectors[ResponsePlanSectors["shelter"] = 2] = "shelter";
    ResponsePlanSectors[ResponsePlanSectors["nutrition"] = 3] = "nutrition";
    ResponsePlanSectors[ResponsePlanSectors["foodSecurityAndLivelihoods"] = 4] = "foodSecurityAndLivelihoods";
    ResponsePlanSectors[ResponsePlanSectors["protection"] = 5] = "protection";
    ResponsePlanSectors[ResponsePlanSectors["education"] = 6] = "education";
    ResponsePlanSectors[ResponsePlanSectors["campManagement"] = 7] = "campManagement";
    ResponsePlanSectors[ResponsePlanSectors["other"] = 8] = "other";
})(ResponsePlanSectors = exports.ResponsePlanSectors || (exports.ResponsePlanSectors = {}));
var PresenceInTheCountry;
(function (PresenceInTheCountry) {
    PresenceInTheCountry[PresenceInTheCountry["currentProgrammes"] = 0] = "currentProgrammes";
    PresenceInTheCountry[PresenceInTheCountry["preExistingPartner"] = 1] = "preExistingPartner";
    PresenceInTheCountry[PresenceInTheCountry["noPreExistingPresence"] = 2] = "noPreExistingPresence";
})(PresenceInTheCountry = exports.PresenceInTheCountry || (exports.PresenceInTheCountry = {}));
var MethodOfImplementation;
(function (MethodOfImplementation) {
    MethodOfImplementation[MethodOfImplementation["fieldStaff"] = 0] = "fieldStaff";
    MethodOfImplementation[MethodOfImplementation["withPartner"] = 1] = "withPartner";
})(MethodOfImplementation = exports.MethodOfImplementation || (exports.MethodOfImplementation = {}));
var PartnerStatus;
(function (PartnerStatus) {
    PartnerStatus[PartnerStatus["AwaitingValidation"] = 0] = "AwaitingValidation";
    PartnerStatus[PartnerStatus["Validated"] = 1] = "Validated";
})(PartnerStatus = exports.PartnerStatus || (exports.PartnerStatus = {}));
var MediaFormat;
(function (MediaFormat) {
    MediaFormat[MediaFormat["photographic"] = 0] = "photographic";
    MediaFormat[MediaFormat["video"] = 1] = "video";
    MediaFormat[MediaFormat["photographicAndVideo"] = 2] = "photographicAndVideo";
})(MediaFormat = exports.MediaFormat || (exports.MediaFormat = {}));
var Gender;
(function (Gender) {
    Gender[Gender["male"] = 0] = "male";
    Gender[Gender["feMale"] = 1] = "feMale";
})(Gender = exports.Gender || (exports.Gender = {}));
var AgeRange;
(function (AgeRange) {
    AgeRange[AgeRange["Less18"] = 0] = "Less18";
    AgeRange[AgeRange["Between18To50"] = 1] = "Between18To50";
    AgeRange[AgeRange["More50"] = 2] = "More50";
})(AgeRange = exports.AgeRange || (exports.AgeRange = {}));
var SourcePlan;
(function (SourcePlan) {
    SourcePlan[SourcePlan["Internationally"] = 0] = "Internationally";
    SourcePlan[SourcePlan["Regionally"] = 1] = "Regionally";
    SourcePlan[SourcePlan["Locally"] = 2] = "Locally";
})(SourcePlan = exports.SourcePlan || (exports.SourcePlan = {}));
var PhonePrefix;
(function (PhonePrefix) {
    PhonePrefix[PhonePrefix["GB"] = 44] = "GB";
    PhonePrefix[PhonePrefix["FR"] = 33] = "FR";
})(PhonePrefix = exports.PhonePrefix || (exports.PhonePrefix = {}));
var Countries;
(function (Countries) {
    Countries[Countries["GB"] = 0] = "GB";
    Countries[Countries["FR"] = 1] = "FR";
    Countries[Countries["DE"] = 2] = "DE";
    Countries[Countries["AF"] = 3] = "AF";
    Countries[Countries["AX"] = 4] = "AX";
    Countries[Countries["AL"] = 5] = "AL";
    Countries[Countries["DZ"] = 6] = "DZ";
    Countries[Countries["AS"] = 7] = "AS";
    Countries[Countries["AD"] = 8] = "AD";
    Countries[Countries["AO"] = 9] = "AO";
    Countries[Countries["AI"] = 10] = "AI";
    Countries[Countries["AQ"] = 11] = "AQ";
    Countries[Countries["AG"] = 12] = "AG";
    Countries[Countries["AR"] = 13] = "AR";
    Countries[Countries["AM"] = 14] = "AM";
    Countries[Countries["AW"] = 15] = "AW";
    Countries[Countries["AU"] = 16] = "AU";
    Countries[Countries["AT"] = 17] = "AT";
    Countries[Countries["AZ"] = 18] = "AZ";
    Countries[Countries["BS"] = 19] = "BS";
    Countries[Countries["BH"] = 20] = "BH";
    Countries[Countries["BD"] = 21] = "BD";
    Countries[Countries["BB"] = 22] = "BB";
    Countries[Countries["BY"] = 23] = "BY";
    Countries[Countries["BE"] = 24] = "BE";
    Countries[Countries["BZ"] = 25] = "BZ";
    Countries[Countries["BJ"] = 26] = "BJ";
    Countries[Countries["BM"] = 27] = "BM";
    Countries[Countries["BT"] = 28] = "BT";
    Countries[Countries["BO"] = 29] = "BO";
    Countries[Countries["BQ"] = 30] = "BQ";
    Countries[Countries["BA"] = 31] = "BA";
    Countries[Countries["BW"] = 32] = "BW";
    Countries[Countries["BV"] = 33] = "BV";
    Countries[Countries["BR"] = 34] = "BR";
    Countries[Countries["IO"] = 35] = "IO";
    Countries[Countries["BN"] = 36] = "BN";
    Countries[Countries["BG"] = 37] = "BG";
    Countries[Countries["BF"] = 38] = "BF";
    Countries[Countries["BI"] = 39] = "BI";
    Countries[Countries["KH"] = 40] = "KH";
    Countries[Countries["CM"] = 41] = "CM";
    Countries[Countries["CA"] = 42] = "CA";
    Countries[Countries["CV"] = 43] = "CV";
    Countries[Countries["KY"] = 44] = "KY";
    Countries[Countries["CF"] = 45] = "CF";
    Countries[Countries["TD"] = 46] = "TD";
    Countries[Countries["CL"] = 47] = "CL";
    Countries[Countries["CN"] = 48] = "CN";
    Countries[Countries["CX"] = 49] = "CX";
    Countries[Countries["CC"] = 50] = "CC";
    Countries[Countries["CO"] = 51] = "CO";
    Countries[Countries["KM"] = 52] = "KM";
    Countries[Countries["CG"] = 53] = "CG";
    Countries[Countries["CD"] = 54] = "CD";
    Countries[Countries["CK"] = 55] = "CK";
    Countries[Countries["CR"] = 56] = "CR";
    Countries[Countries["CI"] = 57] = "CI";
    Countries[Countries["HR"] = 58] = "HR";
    Countries[Countries["CU"] = 59] = "CU";
    Countries[Countries["CW"] = 60] = "CW";
    Countries[Countries["CY"] = 61] = "CY";
    Countries[Countries["CZ"] = 62] = "CZ";
    Countries[Countries["DK"] = 63] = "DK";
    Countries[Countries["DJ"] = 64] = "DJ";
    Countries[Countries["DM"] = 65] = "DM";
    Countries[Countries["DO"] = 66] = "DO";
    Countries[Countries["EC"] = 67] = "EC";
    Countries[Countries["EG"] = 68] = "EG";
    Countries[Countries["SV"] = 69] = "SV";
    Countries[Countries["GQ"] = 70] = "GQ";
    Countries[Countries["ER"] = 71] = "ER";
    Countries[Countries["EE"] = 72] = "EE";
    Countries[Countries["ET"] = 73] = "ET";
    Countries[Countries["FK"] = 74] = "FK";
    Countries[Countries["FO"] = 75] = "FO";
    Countries[Countries["FJ"] = 76] = "FJ";
    Countries[Countries["FI"] = 77] = "FI";
    Countries[Countries["GF"] = 78] = "GF";
    Countries[Countries["PF"] = 79] = "PF";
    Countries[Countries["TF"] = 80] = "TF";
    Countries[Countries["GA"] = 81] = "GA";
    Countries[Countries["GM"] = 82] = "GM";
    Countries[Countries["GE"] = 83] = "GE";
    Countries[Countries["GH"] = 84] = "GH";
    Countries[Countries["GI"] = 85] = "GI";
    Countries[Countries["GR"] = 86] = "GR";
    Countries[Countries["GL"] = 87] = "GL";
    Countries[Countries["GD"] = 88] = "GD";
    Countries[Countries["GP"] = 89] = "GP";
    Countries[Countries["GU"] = 90] = "GU";
    Countries[Countries["GT"] = 91] = "GT";
    Countries[Countries["GG"] = 92] = "GG";
    Countries[Countries["GN"] = 93] = "GN";
    Countries[Countries["GW"] = 94] = "GW";
    Countries[Countries["GY"] = 95] = "GY";
    Countries[Countries["HT"] = 96] = "HT";
    Countries[Countries["HM"] = 97] = "HM";
    Countries[Countries["VA"] = 98] = "VA";
    Countries[Countries["HN"] = 99] = "HN";
    Countries[Countries["HK"] = 100] = "HK";
    Countries[Countries["HU"] = 101] = "HU";
    Countries[Countries["IS"] = 102] = "IS";
    Countries[Countries["IN"] = 103] = "IN";
    Countries[Countries["ID"] = 104] = "ID";
    Countries[Countries["IR"] = 105] = "IR";
    Countries[Countries["IQ"] = 106] = "IQ";
    Countries[Countries["IE"] = 107] = "IE";
    Countries[Countries["IM"] = 108] = "IM";
    Countries[Countries["IL"] = 109] = "IL";
    Countries[Countries["IT"] = 110] = "IT";
    Countries[Countries["JM"] = 111] = "JM";
    Countries[Countries["JP"] = 112] = "JP";
    Countries[Countries["JE"] = 113] = "JE";
    Countries[Countries["JO"] = 114] = "JO";
    Countries[Countries["KZ"] = 115] = "KZ";
    Countries[Countries["KE"] = 116] = "KE";
    Countries[Countries["KI"] = 117] = "KI";
    Countries[Countries["KP"] = 118] = "KP";
    Countries[Countries["KR"] = 119] = "KR";
    Countries[Countries["KW"] = 120] = "KW";
    Countries[Countries["KG"] = 121] = "KG";
    Countries[Countries["LA"] = 122] = "LA";
    Countries[Countries["LV"] = 123] = "LV";
    Countries[Countries["LB"] = 124] = "LB";
    Countries[Countries["LS"] = 125] = "LS";
    Countries[Countries["LR"] = 126] = "LR";
    Countries[Countries["LY"] = 127] = "LY";
    Countries[Countries["LI"] = 128] = "LI";
    Countries[Countries["LT"] = 129] = "LT";
    Countries[Countries["LU"] = 130] = "LU";
    Countries[Countries["MO"] = 131] = "MO";
    Countries[Countries["MK"] = 132] = "MK";
    Countries[Countries["MG"] = 133] = "MG";
    Countries[Countries["MW"] = 134] = "MW";
    Countries[Countries["MY"] = 135] = "MY";
    Countries[Countries["MV"] = 136] = "MV";
    Countries[Countries["ML"] = 137] = "ML";
    Countries[Countries["MT"] = 138] = "MT";
    Countries[Countries["MH"] = 139] = "MH";
    Countries[Countries["MQ"] = 140] = "MQ";
    Countries[Countries["MR"] = 141] = "MR";
    Countries[Countries["MU"] = 142] = "MU";
    Countries[Countries["YT"] = 143] = "YT";
    Countries[Countries["MX"] = 144] = "MX";
    Countries[Countries["FM"] = 145] = "FM";
    Countries[Countries["MD"] = 146] = "MD";
    Countries[Countries["MC"] = 147] = "MC";
    Countries[Countries["MN"] = 148] = "MN";
    Countries[Countries["ME"] = 149] = "ME";
    Countries[Countries["MS"] = 150] = "MS";
    Countries[Countries["MA"] = 151] = "MA";
    Countries[Countries["MZ"] = 152] = "MZ";
    Countries[Countries["MM"] = 153] = "MM";
    Countries[Countries["NA"] = 154] = "NA";
    Countries[Countries["NR"] = 155] = "NR";
    Countries[Countries["NP"] = 156] = "NP";
    Countries[Countries["NL"] = 157] = "NL";
    Countries[Countries["NC"] = 158] = "NC";
    Countries[Countries["NZ"] = 159] = "NZ";
    Countries[Countries["NI"] = 160] = "NI";
    Countries[Countries["NE"] = 161] = "NE";
    Countries[Countries["NG"] = 162] = "NG";
    Countries[Countries["NU"] = 163] = "NU";
    Countries[Countries["NF"] = 164] = "NF";
    Countries[Countries["MP"] = 165] = "MP";
    Countries[Countries["NO"] = 166] = "NO";
    Countries[Countries["OM"] = 167] = "OM";
    Countries[Countries["PK"] = 168] = "PK";
    Countries[Countries["PW"] = 169] = "PW";
    Countries[Countries["PS"] = 170] = "PS";
    Countries[Countries["PA"] = 171] = "PA";
    Countries[Countries["PG"] = 172] = "PG";
    Countries[Countries["PY"] = 173] = "PY";
    Countries[Countries["PE"] = 174] = "PE";
    Countries[Countries["PH"] = 175] = "PH";
    Countries[Countries["PN"] = 176] = "PN";
    Countries[Countries["PL"] = 177] = "PL";
    Countries[Countries["PT"] = 178] = "PT";
    Countries[Countries["PR"] = 179] = "PR";
    Countries[Countries["QA"] = 180] = "QA";
    Countries[Countries["RE"] = 181] = "RE";
    Countries[Countries["RO"] = 182] = "RO";
    Countries[Countries["RU"] = 183] = "RU";
    Countries[Countries["RW"] = 184] = "RW";
    Countries[Countries["BL"] = 185] = "BL";
    Countries[Countries["SH"] = 186] = "SH";
    Countries[Countries["KN"] = 187] = "KN";
    Countries[Countries["LC"] = 188] = "LC";
    Countries[Countries["MF"] = 189] = "MF";
    Countries[Countries["PM"] = 190] = "PM";
    Countries[Countries["VC"] = 191] = "VC";
    Countries[Countries["WS"] = 192] = "WS";
    Countries[Countries["SM"] = 193] = "SM";
    Countries[Countries["ST"] = 194] = "ST";
    Countries[Countries["SA"] = 195] = "SA";
    Countries[Countries["SN"] = 196] = "SN";
    Countries[Countries["RS"] = 197] = "RS";
    Countries[Countries["SC"] = 198] = "SC";
    Countries[Countries["SL"] = 199] = "SL";
    Countries[Countries["SG"] = 200] = "SG";
    Countries[Countries["SX"] = 201] = "SX";
    Countries[Countries["SK"] = 202] = "SK";
    Countries[Countries["SI"] = 203] = "SI";
    Countries[Countries["SB"] = 204] = "SB";
    Countries[Countries["SO"] = 205] = "SO";
    Countries[Countries["ZA"] = 206] = "ZA";
    Countries[Countries["GS"] = 207] = "GS";
    Countries[Countries["SS"] = 208] = "SS";
    Countries[Countries["ES"] = 209] = "ES";
    Countries[Countries["LK"] = 210] = "LK";
    Countries[Countries["SD"] = 211] = "SD";
    Countries[Countries["SR"] = 212] = "SR";
    Countries[Countries["SJ"] = 213] = "SJ";
    Countries[Countries["SZ"] = 214] = "SZ";
    Countries[Countries["SE"] = 215] = "SE";
    Countries[Countries["CH"] = 216] = "CH";
    Countries[Countries["SY"] = 217] = "SY";
    Countries[Countries["TW"] = 218] = "TW";
    Countries[Countries["TJ"] = 219] = "TJ";
    Countries[Countries["TZ"] = 220] = "TZ";
    Countries[Countries["TH"] = 221] = "TH";
    Countries[Countries["TL"] = 222] = "TL";
    Countries[Countries["TG"] = 223] = "TG";
    Countries[Countries["TK"] = 224] = "TK";
    Countries[Countries["TO"] = 225] = "TO";
    Countries[Countries["TT"] = 226] = "TT";
    Countries[Countries["TN"] = 227] = "TN";
    Countries[Countries["TR"] = 228] = "TR";
    Countries[Countries["TM"] = 229] = "TM";
    Countries[Countries["TC"] = 230] = "TC";
    Countries[Countries["TV"] = 231] = "TV";
    Countries[Countries["UG"] = 232] = "UG";
    Countries[Countries["UA"] = 233] = "UA";
    Countries[Countries["AE"] = 234] = "AE";
    Countries[Countries["US"] = 235] = "US";
    Countries[Countries["UM"] = 236] = "UM";
    Countries[Countries["UY"] = 237] = "UY";
    Countries[Countries["UZ"] = 238] = "UZ";
    Countries[Countries["VU"] = 239] = "VU";
    Countries[Countries["VE"] = 240] = "VE";
    Countries[Countries["VN"] = 241] = "VN";
    Countries[Countries["VG"] = 242] = "VG";
    Countries[Countries["VI"] = 243] = "VI";
    Countries[Countries["WF"] = 244] = "WF";
    Countries[Countries["EH"] = 245] = "EH";
    Countries[Countries["YE"] = 246] = "YE";
    Countries[Countries["ZM"] = 247] = "ZM";
    Countries[Countries["ZW"] = 248] = "ZW";
})(Countries = exports.Countries || (exports.Countries = {}));
var ApprovalStatus;
(function (ApprovalStatus) {
    ApprovalStatus[ApprovalStatus["InProgress"] = 0] = "InProgress";
    ApprovalStatus[ApprovalStatus["WaitingApproval"] = 1] = "WaitingApproval";
    ApprovalStatus[ApprovalStatus["Approved"] = 2] = "Approved";
    ApprovalStatus[ApprovalStatus["NeedsReviewing"] = 3] = "NeedsReviewing";
})(ApprovalStatus = exports.ApprovalStatus || (exports.ApprovalStatus = {}));
var Department;
(function (Department) {
    Department[Department["CHS"] = 0] = "CHS";
    Department[Department["Finance"] = 1] = "Finance";
    Department[Department["HR"] = 2] = "HR";
    Department[Department["Logistics"] = 3] = "Logistics";
    Department[Department["Programme"] = 4] = "Programme";
})(Department = exports.Department || (exports.Department = {}));
var HazardCategory;
(function (HazardCategory) {
    HazardCategory[HazardCategory["Earthquake"] = 0] = "Earthquake";
    HazardCategory[HazardCategory["Tsunami"] = 1] = "Tsunami";
    HazardCategory[HazardCategory["Drought"] = 2] = "Drought";
})(HazardCategory = exports.HazardCategory || (exports.HazardCategory = {}));
var AlertMessageType;
(function (AlertMessageType) {
    AlertMessageType[AlertMessageType["Error"] = 0] = "Error";
    AlertMessageType[AlertMessageType["Success"] = 1] = "Success";
})(AlertMessageType = exports.AlertMessageType || (exports.AlertMessageType = {}));
var BudgetCategory;
(function (BudgetCategory) {
    BudgetCategory[BudgetCategory["Inputs"] = 0] = "Inputs";
    BudgetCategory[BudgetCategory["Transport"] = 1] = "Transport";
    BudgetCategory[BudgetCategory["Security"] = 2] = "Security";
    BudgetCategory[BudgetCategory["Logistics"] = 3] = "Logistics";
    BudgetCategory[BudgetCategory["Staffing"] = 4] = "Staffing";
    BudgetCategory[BudgetCategory["Monitoring"] = 5] = "Monitoring";
    BudgetCategory[BudgetCategory["CapitalItems"] = 6] = "CapitalItems";
    BudgetCategory[BudgetCategory["ManagementSupport"] = 7] = "ManagementSupport";
})(BudgetCategory = exports.BudgetCategory || (exports.BudgetCategory = {}));
var ActionStatus;
(function (ActionStatus) {
    ActionStatus[ActionStatus["Expired"] = 0] = "Expired";
    ActionStatus[ActionStatus["InProgress"] = 1] = "InProgress";
    ActionStatus[ActionStatus["Completed"] = 2] = "Completed";
    ActionStatus[ActionStatus["Inactive"] = 3] = "Inactive";
})(ActionStatus = exports.ActionStatus || (exports.ActionStatus = {}));
var SizeType;
(function (SizeType) {
    SizeType[SizeType["KB"] = 0] = "KB";
    SizeType[SizeType["MB"] = 1] = "MB";
})(SizeType = exports.SizeType || (exports.SizeType = {}));
var AlertLevels;
(function (AlertLevels) {
    AlertLevels[AlertLevels["Green"] = 0] = "Green";
    AlertLevels[AlertLevels["Amber"] = 1] = "Amber";
    AlertLevels[AlertLevels["Red"] = 2] = "Red";
})(AlertLevels = exports.AlertLevels || (exports.AlertLevels = {}));
var GeoLocation;
(function (GeoLocation) {
    GeoLocation[GeoLocation["national"] = 0] = "national";
    GeoLocation[GeoLocation["subnational"] = 1] = "subnational";
})(GeoLocation = exports.GeoLocation || (exports.GeoLocation = {}));
var ThresholdName;
(function (ThresholdName) {
    ThresholdName[ThresholdName["Green"] = 0] = "Green";
    ThresholdName[ThresholdName["Amber"] = 1] = "Amber";
    ThresholdName[ThresholdName["Red"] = 2] = "Red";
})(ThresholdName = exports.ThresholdName || (exports.ThresholdName = {}));
var AlertStatus;
(function (AlertStatus) {
    AlertStatus[AlertStatus["WaitingResponse"] = 0] = "WaitingResponse";
    AlertStatus[AlertStatus["Approved"] = 1] = "Approved";
    AlertStatus[AlertStatus["Rejected"] = 2] = "Rejected";
})(AlertStatus = exports.AlertStatus || (exports.AlertStatus = {}));
var DashboardType;
(function (DashboardType) {
    DashboardType[DashboardType["default"] = 0] = "default";
    DashboardType[DashboardType["director"] = 1] = "director";
})(DashboardType = exports.DashboardType || (exports.DashboardType = {}));
